# config.yml

backend:
  name: github
  repo: chonghua/chonghua.github.io
  branch: main # Branch to update (optional; defaults to master)
media_folder: 'assets/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - { name: 标题 }
